<?php

namespace app\models;

use Faker\Provider\Image;
use Yii;
use yii\base\InvalidConfigException;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "article".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $description
 * @property string|null $content
 * @property string|null $date
 * @property string|null $image
 * @property int|null $viewed
 * @property int|null $user_id
 * @property int|null $status
 * @property int|null $category_id
 *
 * @property ArticleTag[] $articleTags
 * @property Comment[] $comments
 */
class Article extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'article';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['title', 'description', 'content'], 'string'],
            [['date'], 'date', 'format' => 'php:Y-m-d'],
            [['date'], 'default', 'value' => date('Y-m-d')],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'content' => 'Content',
            'date' => 'Date',
            'image' => 'Image',
            'viewed' => 'Viewed',
            'user_id' => 'User ID',
            'status' => 'Status',
            'category_id' => 'Category ID',
        ];
    }

    public function saveImage($filename)
    {
        $this->image = $filename;
        return $this->save(false);
    }

    public function getImage()
    {
        return $this->image ? '/uploads/' . $this->image : '/no-image.jpeg';
    }

    public function deleteImage()
    {
        $imageUpload = new ImageUpload();
        $imageUpload->deleteCurrentImage($this->image);
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    public function saveCategory($category_id)
    {
        $category = Category::findOne($category_id);

        if ($category != null)
        {
            $this->link('category', $category);
            return true;
        }
    }

    public function getTags()
    {
        try {
            return $this->hasMany(Tag::className(), ['id' => 'tag_id'])
                ->viaTable('article_tag', ['article_id' => 'id']);
        } catch (InvalidConfigException $e) {
        }
    }

    public function clearCurrentTags()
    {
        ArticleTag::deleteAll(['article_id'=>$this->id]);
    }

    public function getSelectedTags()
    {
        $selectedIds = $this->getTags()->select('id')->asArray()->all();
        return ArrayHelper::getColumn($selectedIds, 'id');
    }

    public function saveTags($tags)
    {
        if (is_array($tags))
        {
            $this->clearCurrentTags();

            foreach($tags as $tag_id)
            {
                $tag = Tag::findOne($tag_id);
                $this->link('tags', $tag);
            }
        }
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

//    /**
//     * Gets query for [[ArticleTags]].
//     *
//     * @return \yii\db\ActiveQuery
//     */
//    public function getArticleTags()
//    {
//        return $this->hasMany(ArticleTag::class, ['article_id' => 'id']);
//    }
//
//    /**
//     * Gets query for [[Comments]].
//     *
//     * @return \yii\db\ActiveQuery
//     */
//    public function getComments()
//    {
//        return $this->hasMany(Comment::class, ['article_id' => 'id']);
//    }
}
